Auth/urls.py
from django.urls import path
from .views import Signup, Login, logout_view, forgot_password,reset_password
app_name = 'Auth'

urlpatterns = [
    path('signup/', Signup.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    path('reset_password/', reset_password, name='reset_password'),
]

GreenCart/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
admin.site.site_header="GreenCart Admin"
admin.site.site_title ="GreenCart Admin Portal"
from payments.views import payment_view, payment_success

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GreenCartEcom.urls','GreenCartEcom'), name='GreenCartEcom'),
    path('cart/', include('add_to_cart.urls', 'AddToCart'), name='AddToCart'),
    path('auth/', include('Auth.urls','Auth'), name='Auth'),
    path('shop/', include('Shop.urls','Shop'), name='Shop'),
    path('profile/', include('userprofile.urls','Profile'), name='Profile'),
    path('pay/', include(('payments.urls', 'payments'), namespace='payments')),
    path('support/', include('Support.urls'), name='Support')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from .views import clear_search_history, home, product_detail, product_list, create_product, edit_product, delete_product, manage_reviews, delete_review ,edit_review

app_name = 'Shop'

urlpatterns = [
    path('',home, name='home'),
    path('cart/',home, name='cart'),
    path('checkout/',home, name='checkout'),
    path('order/',home, name='order'),
    path('profile/',home, name='profile'),
    path('product-detail/<int:id>', product_detail, name='product_detail'),
    path('mylistings/', product_list, name='product_list'),
    path('create_product/', create_product, name='create_product'),
    path('edit_product/<int:product_id>/', edit_product, name='edit_product'),
    path('delete_product/', delete_product, name='delete_product'),
    path('clear_search_history/', clear_search_history, name='clear_search_history'),
    path('manage_reviews/',manage_reviews, name='manage_reviews'),
    path('edit/<int:review_id>/', edit_review, name='edit_review'),
    path('delete/<int:review_id>/', delete_review, name='delete_review'),
]

add_to_cart/urls.py
from django.urls import path
from . import views

app_name = 'add_to_cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('increment/<int:cart_item_id>/', views.increment_quantity, name='increment_quantity'),
    path('decrement/<int:cart_item_id>/', views.decrement_quantity, name='decrement_quantity'),
    path('add_to_wishlist/<int:cart_item_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('remove_from_wishlist/<int:wishlist_item_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('add_to_wishlist/product/<int:product_id>/', views.add_to_wishlist, name='add_product_wishlist'),
    path('add_from_wishlist/<int:product_id>/', views.add_to_cart_from_wishlist, name='add_to_cart_from_wishlist'),
]

payments/urls.py
from django.contrib import admin
from django.urls import path
from payments.views import payment_view, payment_success, payment_failed, order_summary, checkout

app_name = 'payments'
urlpatterns = [
    path('payment/', payment_view, name='payment_form'),
    path('order/<int:payment_id>/', order_summary, name='order_view'),
    path('checkout/<int:payment_id>/', checkout, name='checkout'),
    path('success/', payment_success, name='payment_success'),
    path('failed/<int:payment_id>/', payment_failed, name='payment_failed'),
]

add_to_cart/models.py
from django.db import models

from Shop.models import Product


# Create your models here.

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    user_id = models.CharField(max_length=10,default="1")

    def __str__(self):
        return f"{self.quantity} x {self.product.name}"

    def total_price(self):
        return self.quantity * self.product.discount_price


class WishlistItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user_id = models.CharField(max_length=10,default="1")

    def __str__(self):
        return self.product.name

add_to_cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from Shop.models import Product
from userprofile.models import UserProfile
from .models import CartItem, WishlistItem
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import datetime

@login_required
def cart_view(request):
    cart_items = CartItem.objects.filter(product__expiry_date__gte=datetime.now(), user_id=request.user.id)
    total_amount = sum(item.total_price() for item in cart_items)
    total_items = sum(item.quantity for item in cart_items)
    return render(request, 'Cart/cart.html',
                  {'cart_items': cart_items, 'total_amount': total_amount, 'total_items': total_items,
                   'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url})


@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart_item, created = CartItem.objects.get_or_create(product=product)
    if not created:
        cart_item.quantity += 1
    cart_item.user_id = request.user.id
    cart_item.save()
    messages.success(request, 'Product added to cart')
    return redirect('Shop:home')


@login_required
def add_to_cart_from_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart_item, created = CartItem.objects.get_or_create(product=product)
    if not created:
        cart_item.quantity += 1
    cart_item.user_id = request.user.id
    cart_item.save()
    messages.success(request, 'Product added to cart')
    return redirect('add_to_cart:wishlist')


@login_required
def remove_from_cart(request, cart_item_id):
    cart_item = get_object_or_404(CartItem, id=cart_item_id)
    cart_item.delete()
    return redirect('add_to_cart:cart')


@login_required
def increment_quantity(request, cart_item_id):
    cart_item = get_object_or_404(CartItem, id=cart_item_id)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('add_to_cart:cart')


@login_required
def decrement_quantity(request, cart_item_id):
    cart_item = get_object_or_404(CartItem, id=cart_item_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('add_to_cart:cart')


@login_required
def add_to_wishlist(request, cart_item_id=None, product_id=None):
    global cart_item
    if cart_item_id:
        cart_item = get_object_or_404(CartItem, id=cart_item_id)
        product = cart_item.product
    elif product_id:
        product = get_object_or_404(Product, id=product_id)
    else:
        messages.error(request, 'Invalid operation.')
        return redirect('Shop:home')

    # Check if the product is already in the wishlist
    if WishlistItem.objects.filter(product=product, user_id=request.user.id).exists():
        messages.success(request, 'Product is already in your wishlist')
    else:
        WishlistItem.objects.create(product=product, user_id=request.user.id)
        messages.success(request, 'Product added to wishlist')

        if cart_item_id:
            cart_item.delete()
            return redirect('add_to_cart:cart')

    return redirect('Shop:home')


@login_required
def wishlist_view(request):
    wishlist_items = WishlistItem.objects.filter(product__expiry_date__gte=datetime.now(), user_id=request.user.id)
    return render(request, 'Cart/wishlist.html', {'wishlist_items': wishlist_items,
                                                  'user_profile_pic': UserProfile.objects.get(
                                                      user=request.user).profile_pic.url})


@login_required
def remove_from_wishlist(request, wishlist_item_id):
    wishlist_item = get_object_or_404(WishlistItem, id=wishlist_item_id)
    wishlist_item.delete()
    return redirect('add_to_cart:wishlist')

add_to_cart/templates/Cart/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Add To Cart{% endblock %}</title>
    <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    <!-- Load Tailwind CSS from CDN -->
    <script src="https://cdn.tailwindcss.com/"></script>
    <!-- Load custom CSS file -->
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <style>
        body {
            /* Set light green background color */
            background-color: #e0f2e9;
        }
    </style>
</head>

<body class="bg-gray-100 flex flex-col min-h-screen">
    {% include 'alert.html' %}
    <header>
        {% include 'Shop/navbar.html' %}
    </header>
    <main class="flex-grow">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="bg-gray-800 text-white">
        {% include 'footer.html' %}
    </footer>
</body>

</html>

add_to_cart/templates/Cart/cart.html
{% extends "Cart/base.html" %}

{% block title %}Shopping Cart{% endblock %}



{% block content %}

<style>
    .wish-list-icon:hover {
        fill: red;
    }
</style>


<div class="container mx-auto mt-10">
    <div class="flex shadow-md my-10 rounded-lg">
        <div class="w-full bg-white px-10 py-10 rounded-lg">
            <!-- Shopping Cart Header -->
            <div class="flex justify-between border-b pb-8">
                <h1 class="font-semibold text-3xl text-green-700">Shopping Cart 🛒</h1>
                <h2 class="font-semibold text-2xl text-green-700">Total: {{ total_items }} Items</h2>
            </div>
        {% if cart_items %}
            <!-- Cart Columns Header -->
            <div class="flex mt-10 mb-5">
                <h3 class="font-semibold text-gray-600 text-sm uppercase w-2/5">Product Details</h3>
                <h3 class="font-semibold text-center text-gray-600 text-sm uppercase w-1/5 text-center">Quantity</h3>
                <h3 class="font-semibold text-center text-gray-600 text-sm uppercase w-1/5 text-center">Price</h3>
                <h3 class="font-semibold text-center text-gray-600 text-sm uppercase w-1/5 text-center">Total</h3>
                <h3 class="font-semibold text-center text-gray-600 text-sm uppercase w-1/5 text-center">Actions</h3>
            </div>
            <!-- Cart Items -->
            {% for item in cart_items %}
            <div class="flex items-center hover:bg-gray-100 -mx-8 px-6 py-5">
                <div class="flex w-2/5">
                    <div class="w-30">
                        <img class="w-20" src="{{ item.product.image.url }}" alt="product">
                    </div>
                    <div class="flex flex-col justify-between ml-4 flex-grow">
                        <span class="font-bold text-md text-gray-600">{{ item.product.name }}</span>
                        <form action="{% url 'add_to_cart:remove_from_cart' item.id %}" method="POST">
                            {% csrf_token %}
                            {% comment %} <button type="submit" class="font-semibold hover:text-green-600 text-red-500 text-xs">Remove</button> {% endcomment %}
                            <button type="submit" class="bg-gray-600 text-white py-1 px-3 rounded-lg text-xs font-semibold hover:bg-red-600 hover:text-white flex items-center justify-center">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                                </svg>
                                Remove
                            </button>  
                        </form>
                    </div>
                </div>
                <div class="flex justify-center w-1/5">
                    <form action="{% url 'add_to_cart:decrement_quantity' item.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit">
                            <svg class="fill-current text-green-600 w-4 mt-2 mx-3 cursor-pointer" viewBox="0 0 448 512">
                                <path d="M416 208H32c-17.67 0-32 14.33-32 32s14.33 32 32 32h384c17.67 0 32-14.33 32-32s-14.33-32-32-32z"/>
                            </svg>
                        </button>
                    </form>
                    <input class="mx-2 border text-center w-10 h-10" type="text" name="quantity" value="{{ item.quantity }}" min="1">
                    <form action="{% url 'add_to_cart:increment_quantity' item.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit">
                            <svg class="fill-current text-green-600 w-4 mt-2 mx-3 cursor-pointer" viewBox="0 0 448 512">
                                <path d="M416 208H240V32c0-17.67-14.33-32-32-32s-32 14.33-32 32v176H32c-17.67 0-32 14.33-32 32s14.33 32 32 32h144v176c0 17.67 14.33 32 32 32s32-14.33 32-32V272h176c17.67 0 32-14.33 32-32s-14.33-32-32-32z"/>
                            </svg>
                        </button>
                    </form>
                </div>
                <span class="text-center w-1/5 font-semibold text-md text-gray-600">${{ item.product.discount_price }}</span>
                <span class="text-center w-1/5 font-semibold text-md text-gray-600">${{ item.total_price }}</span>
                <div class="text-center w-1/5">
                    <form action="{% url 'add_to_cart:add_to_wishlist' item.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="font-semibold bg-white py-1 px-3 rounded-lg text-red-500 hover:text-white hover:bg-gray-600 text-md flex items-center justify-center hover:fill-red-500">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2 wish-list-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                            </svg>
                            Add to Wish List
                        </button>     
                    </form>
                </div>
            </div>
            {% endfor %}
            <!-- Continue Shopping and Total Amount -->
            <div class="flex justify-between mt-10">
                <div class="w-1/2">
                    <a href="{% url 'Shop:home' %}" class="flex font-semibold text-green-600 text-sm mt-10">
                        <svg class="fill-current mr-2 text-green-600 w-4" viewBox="0 0 448 512"><path d="M134.059 296H416c17.673 0 32-14.327 32-32s-14.327-32-32-32H134.059l76.218-76.218c12.499-12.499 12.499-32.757 0-45.255s-32.757-12.499-45.255 0L32.273 240.573c-6.248 6.248-9.373 14.439-9.373 22.628s3.125 16.379 9.373 22.628l132.748 132.748c12.499 12.499 32.757 12.499 45.255 0s12.499-32.757 0-45.255L134.059 296z"/></svg>
                        Continue Shopping
                    </a>
                </div>
                <div class="flex justify-end w-1/2">
                    <div class="flex items-center">
                        <span class="font-semibold text-md">Total:</span>&nbsp;&nbsp;<span class="font-semibold text-green-600 text-3xl"> ${{ total_amount }} </span>
                    </div>
                </div>
            </div>
            <!-- Proceed to Checkout Button -->
            <div class="flex justify-end mt-10">
                <a href="{% url 'payments:payment_form' %}" class="bg-green-600 flex font-semibold hover:bg-green-700 items-center px-5 py-2 rounded-lg text-white text-sm">
                    Proceed to Payment
                </a>
            </div>
        {% else %}
        <!-- Empty Cart Message -->
            <div class="bg-white p-4 rounded-lg shadow-lg mt-6">
                <p class="text-xl font-semibold text-gray-700">Your cart is empty.</p>
                <a href="{% url 'Shop:home' %}" class="mt-4 inline-block py-2 px-4 bg-green-600 text-white rounded-lg hover:bg-green-700">Continue Shopping</a>
            </div>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

add_to_cart/templates/Cart/wishlist.html
{% extends "Cart/base.html" %}

{% block title %}Wishlist{% endblock %}

{% block content %}
<div class="container mx-auto mt-10">
    <div class="shadow-md my-10 rounded-lg">
        <div class="w-full bg-white px-10 py-10 rounded-lg">
            <div class="flex justify-between border-b pb-8">
                <h1 class="font-semibold text-3xl text-green-700">Wishlist 💚</h1>
                <h2 class="font-semibold text-2xl text-green-700">Total: {{ wishlist_items|length }} Items</h2>
            </div>
            {% if wishlist_items %}
                <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mt-10">
                    {% for item in wishlist_items %}
                    <div class="group relative mx-auto my-6 w-full max-w-xs flex flex-col overflow-hidden rounded-lg bg-white shadow-m">
                        <div class="h-48 w-full overflow-hidden"> <!-- Fixed height container for the image -->
                            <img class="object-cover h-full w-full transform transition-transform duration-500 group-hover:scale-110" src="{{ item.product.image.url }}" alt="product"/>
                        </div>
                        <div class="flex flex-col justify-between flex-1">
                            <div class="mt-4 px-4">
                                <span class="font-bold text-md text-gray-600">{{ item.product.name }}</span>
                            </div>
                            <div class="mt-4 px-4 mb-4 flex justify-between items-center">
                                <form action="{% url 'add_to_cart:add_to_cart_from_wishlist' item.product.id %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="bg-gray-600 text-white py-1 px-3 rounded-lg text-sm font-semibold hover:bg-gray-900 flex items-center justify-center">
                                        ⮐ Move to Cart
                                    </button>                                
                                </form>
                                <form action="{% url 'add_to_cart:remove_from_wishlist' item.id %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="bg-red-600 text-white py-1 px-3 rounded-lg text-sm font-semibold hover:bg-red-700 flex items-center justify-center">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                                        </svg>
                                        Remove
                                    </button>                                
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>




                <div class="flex justify-between mt-10">
                    <div class="w-1/2">
                        <a href="{% url 'Shop:home' %}" class="flex font-semibold text-green-600 text-sm mt-10">
                            <svg class="fill-current mr-2 text-green-600 w-4" viewBox="0 0 448 512"><path d="M134.059 296H416c17.673 0 32-14.327 32-32s-14.327-32-32-32H134.059l76.218-76.218c12.499-12.499 12.499-32.757 0-45.255s-32.757-12.499-45.255 0L32.273 240.573c-6.248 6.248-9.373 14.439-9.373 22.628s3.125 16.379 9.373 22.628l132.748 132.748c12.499 12.499 32.757 12.499 45.255 0s12.499-32.757 0-45.255L134.059 296z"/></svg>
                            Continue Shopping
                        </a>
                    </div>
                </div>
            {% else %}
                <div class="bg-white p-4 rounded-lg shadow-lg mt-6">
                    <p class="text-xl font-semibold text-gray-700">Your wishlist is empty.</p>
                    <a href="{% url 'Shop:home' %}" class="mt-4 inline-block py-2 px-4 bg-green-600 text-white rounded-lg hover:bg-green-700">Continue Shopping</a>
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}