Auth/urls.py
from django.urls import path
from .views import Signup, Login, logout_view, forgot_password,reset_password
app_name = 'Auth'

urlpatterns = [
    path('signup/', Signup.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    path('reset_password/', reset_password, name='reset_password'),
]

GreenCart/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
admin.site.site_header="GreenCart Admin"
admin.site.site_title ="GreenCart Admin Portal"
from payments.views import payment_view, payment_success

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GreenCartEcom.urls','GreenCartEcom'), name='GreenCartEcom'),
    path('cart/', include('add_to_cart.urls', 'AddToCart'), name='AddToCart'),
    path('auth/', include('Auth.urls','Auth'), name='Auth'),
    path('shop/', include('Shop.urls','Shop'), name='Shop'),
    path('profile/', include('userprofile.urls','Profile'), name='Profile'),
    path('pay/', include(('payments.urls', 'payments'), namespace='payments')),
    path('support/', include('Support.urls'), name='Support')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from .views import clear_search_history, home, product_detail, product_list, create_product, edit_product, delete_product, manage_reviews, delete_review ,edit_review

app_name = 'Shop'

urlpatterns = [
    path('',home, name='home'),
    path('cart/',home, name='cart'),
    path('checkout/',home, name='checkout'),
    path('order/',home, name='order'),
    path('profile/',home, name='profile'),
    path('product-detail/<int:id>', product_detail, name='product_detail'),
    path('mylistings/', product_list, name='product_list'),
    path('create_product/', create_product, name='create_product'),
    path('edit_product/<int:product_id>/', edit_product, name='edit_product'),
    path('delete_product/', delete_product, name='delete_product'),
    path('clear_search_history/', clear_search_history, name='clear_search_history'),
    path('manage_reviews/',manage_reviews, name='manage_reviews'),
    path('edit/<int:review_id>/', edit_review, name='edit_review'),
    path('delete/<int:review_id>/', delete_review, name='delete_review'),
]

payments/urls.py
from django.contrib import admin
from django.urls import path
from payments.views import payment_view, payment_success, payment_failed, order_summary, checkout

app_name = 'payments'
urlpatterns = [
    path('payment/', payment_view, name='payment_form'),
    path('order/<int:payment_id>/', order_summary, name='order_view'),
    path('checkout/<int:payment_id>/', checkout, name='checkout'),
    path('success/', payment_success, name='payment_success'),
    path('failed/<int:payment_id>/', payment_failed, name='payment_failed'),
]

payments/models.py
from django.db import models
import uuid
# Define choices for country and city
COUNTRY_CHOICES = [
    ('USA', 'United States'),
    ('CAN', 'Canada'),
    ('UK', 'United Kingdom'),
    ('AUS', 'Australia'),
    ('GER', 'Germany'),
    ('FRA', 'France'),
    ('ITA', 'Italy'),
    ('ESP', 'Spain'),
    ('JPN', 'Japan'),
    ('CHN', 'China'),
    ('IND', 'India'),
    ('BRA', 'Brazil'),
    ('RUS', 'Russia'),
    ('MEX', 'Mexico'),
    ('RSA', 'South Africa'),
    ('NIG', 'Nigeria'),
    ('EGY', 'Egypt'),
    ('ARG', 'Argentina'),
    ('CHL', 'Chile'),
    ('COL', 'Colombia'),
    ('SWE', 'Sweden'),
    ('NOR', 'Norway'),
    ('DEN', 'Denmark'),
    ('FIN', 'Finland'),
    ('POL', 'Poland'),
    ('TUR', 'Turkey'),
    ('KOR', 'South Korea'),
    ('SGP', 'Singapore'),
    ('MYS', 'Malaysia'),
    ('THA', 'Thailand'),
    ('VNM', 'Vietnam'),
    ('PHL', 'Philippines'),
    ('IDN', 'Indonesia'),
    ('NZL', 'New Zealand'),
    ('SAU', 'Saudi Arabia'),
    ('ISR', 'Israel'),
    ('UAE', 'United Arab Emirates'),
    ('IRN', 'Iran'),
    ('PAK', 'Pakistan'),
    ('BGD', 'Bangladesh'),
    ('UKR', 'Ukraine'),
    ('BEL', 'Belgium'),
    ('NLD', 'Netherlands'),
    ('CHE', 'Switzerland'),
    ('AUT', 'Austria'),
    ('GRC', 'Greece'),
    ('HUN', 'Hungary'),
    ('CZE', 'Czech Republic'),
    ('PRT', 'Portugal'),
    ('ROU', 'Romania'),
]

CITY_CHOICES = [
    ('NYC', 'New York City'),
    ('LAX', 'Los Angeles'),
    ('CHI', 'Chicago'),
    ('HOU', 'Houston'),
    ('PHX', 'Phoenix'),
    ('TOR', 'Toronto'),
    ('VAN', 'Vancouver'),
    ('MTL', 'Montreal'),
    ('LDN', 'London'),
    ('MAN', 'Manchester'),
    ('SYD', 'Sydney'),
    ('MEL', 'Melbourne'),
    ('BER', 'Berlin'),
    ('MUC', 'Munich'),
    ('PAR', 'Paris'),
    ('LYO', 'Lyon'),
    ('ROM', 'Rome'),
    ('MIL', 'Milan'),
    ('MAD', 'Madrid'),
    ('BCN', 'Barcelona'),
    ('TOK', 'Tokyo'),
    ('OSA', 'Osaka'),
    ('BJS', 'Beijing'),
    ('SHA', 'Shanghai'),
    ('DEL', 'Delhi'),
    ('MUM', 'Mumbai'),
    ('RIO', 'Rio de Janeiro'),
    ('SAO', 'Sao Paulo'),
    ('MOW', 'Moscow'),
    ('SPB', 'Saint Petersburg'),
    ('MEX', 'Mexico City'),
    ('GDL', 'Guadalajara'),
    ('JHB', 'Johannesburg'),
    ('CPT', 'Cape Town'),
    ('LOS', 'Lagos'),
    ('CAI', 'Cairo'),
    ('BUE', 'Buenos Aires'),
    ('SCL', 'Santiago'),
    ('BOG', 'Bogota'),
    ('STO', 'Stockholm'),
    ('OSL', 'Oslo'),
    ('CPH', 'Copenhagen'),
    ('HEL', 'Helsinki'),
    ('WAW', 'Warsaw'),
    ('IST', 'Istanbul'),
    ('SEL', 'Seoul'),
    ('SIN', 'Singapore'),
    ('KUL', 'Kuala Lumpur'),
    ('BKK', 'Bangkok'),
    ('HAN', 'Hanoi'),  # Added Vietnamese cities
    ('HCM', 'Ho Chi Minh City'),  # Added Vietnamese cities
    ('WIN', 'Windsor')
]


class Payment(models.Model):
    Name = models.CharField(max_length=255, default="Jack Ryan")
    address = models.CharField(max_length=264, blank=True, default="300 Ouellette Avenue")
    zipcode = models.CharField(max_length=10, blank=True, default="N9A 7B4")
    country = models.CharField(max_length=264, choices=COUNTRY_CHOICES, blank=True, default='CAN')
    city = models.CharField(max_length=264, choices=CITY_CHOICES, blank=True, default='WIN')
    # Amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    Email = models.EmailField(default="test@greencart.ca")
    stripe_payment_intent_id = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.Email}"


class Order(models.Model):
    order_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    total_items = models.IntegerField()
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE, related_name='orders', null=True, blank=True)

    def __str__(self):
        return f'Order {self.order_id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.CharField(max_length=100)  # Or use a ForeignKey to a Product model if you have one
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def total_price(self):
        return self.quantity * self.price

    def __str__(self):
        return f'{self.product} ({self.quantity})'

payments/forms.py
from django import forms
from .models import Payment

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['Name', 'address', 'zipcode', 'country', 'city', 'Email']
        widgets = {
            'Name': forms.TextInput(attrs={'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-green-500'}),
            'address': forms.TextInput(attrs={'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-green-500'}),
            'zipcode': forms.TextInput(attrs={'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-green-500'}),
            'country': forms.Select(attrs={'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-green-500'}),
            'city': forms.Select(attrs={'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-green-500'}),
            'Email': forms.EmailInput(attrs={'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-green-500'}),
        }

payments/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from add_to_cart.models import CartItem
from userprofile.models import UserProfile
from .models import Order, OrderItem, Payment
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .forms import PaymentForm
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY


@login_required
def payment_view(request):
    form = PaymentForm()
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        if form.is_valid():
            payment = form.save(commit=False)
            payment.save()
            return redirect('payments:order_view', payment_id=payment.id)
    return render(request, 'payments/payment_form.html', {'form': form, 'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url})


@login_required
def payment_success(request):
    CartItem.objects.all().delete()
    return render(request, 'payments/payment_success.html', {'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url})


@login_required
def payment_failed(request, payment_id):
    return render(request, 'payments/payment_failed.html', {'payment_id': payment_id, 'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url})


@login_required
def order_summary(request, payment_id):
    payment = Payment.objects.get(id=payment_id)
    cart_items = CartItem.objects.all()
    total_amount = sum(item.total_price() for item in cart_items)
    total_items = sum(item.quantity for item in cart_items)

    return render(request, 'payments/order_summary.html', {
        'cart_items': cart_items,
        'total_amount': total_amount,
        'total_items': total_items,
        'payment': payment,
        'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url
    })


@login_required
def checkout(request, payment_id):
    payment = Payment.objects.get(id=payment_id)
    total_amount = sum(item.total_price() for item in CartItem.objects.all())
    total_items = sum(item.quantity for item in CartItem.objects.all())

    order = Order.objects.create(total_amount=total_amount, total_items=total_items, payment=payment)
    for item in CartItem.objects.all():
        OrderItem.objects.create(
            order=order,
            product=item.product.name,
            quantity=item.quantity,
            price=item.product.price,
        )

    payment_intent = stripe.PaymentIntent.create(
        amount=int(total_amount * 100),
        currency='cad',
        metadata={'email': payment.Email}
    )

    payment.stripe_payment_intent_id = payment_intent['id']
    payment.save()

    return render(request, 'payments/checkout.html', {
        'payment_intent_client_secret': payment_intent['client_secret'],
        'STRIPE_PUBLISHABLE_KEY': settings.STRIPE_PUBLISHABLE_KEY,
        'payment': payment,
        'total_amount': total_amount,
        'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url
    })

payments/templates/payments/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    <script src="https://cdn.tailwindcss.com/"></script>
{#    <link rel="stylesheet" href="{% static 'css/app.css' %}">#}
    <script src="https://js.stripe.com/v3/"></script>
    {% block extra_css %}{% endblock %}
</head>
<style>
    body {
        background-color: white;
    }
</style>
<body>
    {% include 'Shop/navbar.html' %}
    <div class="">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="bg-gray-800 text-white">
        {% include 'footer.html' %}
    </footer>
</body>
</html>

payments/templates/payments/checkout.html
{% extends 'payments/base.html' %}
{% load static %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h1 class="text-4xl font-extrabold mb-8 text-center text-green-700">Checkout</h1>
    <form id="payment-form" class="max-w-xl mx-auto bg-white p-8 rounded-lg shadow-lg space-y-6" method="post">
        {% csrf_token %}
        <input type="hidden" id="payment_id" name="payment_id" value="{{ payment.id }}">

        <div class="mb-6">
            <label for="name" class="block text-gray-700 text-lg font-medium mb-2">Name on Card</label>
            <input type="text" id="name" name="name" value="{{ payment.Name }}" required class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500 transition duration-300">
        </div>

        <div class="mb-6">
            <label for="email" class="block text-gray-700 text-lg font-medium mb-2">Email</label>
            <input type="email" id="email" name="email" value="{{ payment.Email }}" required class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500 transition duration-300">
        </div>

        <div class="mb-6">
            <label for="amount" class="block text-gray-700 text-lg font-medium mb-2">Total Amount</label>
            <input type="number" id="amount" name="total_amount" value="{{ total_amount }}" required class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500 transition duration-300">
        </div>

        <div class="mb-6">
            <label for="zipcode" class="block text-gray-700 text-lg font-medium mb-2">Zip Code</label>
            <input type="text" id="zipcode" name="zipcode" value="{{ payment.zipcode }}" required class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500 transition duration-300">
        </div>

        <div id="card-element" class="mb-6 p-4 border border-gray-300 rounded-lg">
            <!-- A Stripe Element will be inserted here. -->
        </div>

        <div id="card-error" role="alert" class="text-red-500 mb-4"></div>

        <button id="submit" class="w-full bg-green-800 text-white py-3 px-4 rounded-lg shadow-md hover:bg-green-800 transition duration-300">Pay</button>
    </form>
</div>

<script>
    // Initialize Stripe
    var stripe = Stripe('{{ STRIPE_PUBLISHABLE_KEY }}'); // Replace with your Stripe publishable key
    var elements = stripe.elements();

    // Create an instance of the card Element
    var cardElement = elements.create('card', {
        hidePostalCode: true
    });

    // Add an instance of the card Element into the `card-element` <div>
    cardElement.mount('#card-element');

    // Handle real-time validation errors from the card Element
    cardElement.on('change', function(event) {
        var displayError = document.getElementById('card-error');
        if (event.error) {
            displayError.textContent = event.error.message;
        } else {
            displayError.textContent = '';
        }
    });

    // Handle form submission
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
        event.preventDefault();

        stripe.confirmCardPayment('{{ payment_intent_client_secret }}', {
            payment_method: {
                card: cardElement,
                billing_details: {
                    name: form.querySelector('input[name="name"]').value,
                    email: form.querySelector('input[name="email"]').value,
                }
            }
        }).then(function(result) {
            if (result.error) {
                var paymentId = document.getElementById('payment_id').value;
                window.location.href = "/pay/failed/" + paymentId + "/";
            } else {
                // The payment succeeded!
                window.location.href = "{% url 'payments:payment_success' %}";
            }
        });
    });
</script>
{% endblock %}

payments/templates/payments/order_summary.html
{% extends 'payments/base.html' %}
{% load static %}

{% block title %}Order Summary{% endblock %}

{% block content %}
<div class="container mx-auto p-16">
    <div class="bg-white rounded-lg shadow-lg p-6">
        <h2 class="text-2xl text-green-700 font-bold mb-4">Order Summary</h2>
        <div class="overflow-x-auto">
            <table class="min-w-full rounded-lg border border-gray-300 overflow-hidden">
                <thead>
                    <tr class="bg-green-50">
                        <th class="py-3 px-6 text-gray-700 font-semibold uppercase text-sm text-left">Item</th>
                        <th class="py-3 px-6 text-gray-700 font-semibold uppercase text-sm text-left">Image</th>
                        <th class="py-3 px-6 text-gray-700 font-semibold uppercase text-sm text-left">Quantity</th>
                        <th class="py-3 px-6 text-gray-700 font-semibold uppercase text-sm text-left">Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_items %}
                    <tr>
                        <td class="py-3 px-6 border-b border-gray-300">{{ item.product.name }}</td>
                        <td class="py-3 px-6 border-b border-gray-300">
                            <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" class="w-16 h-16 object-cover rounded-lg border border-gray-200">
                        </td>
                        <td class="py-3 px-6 border-b border-gray-300">{{ item.quantity }}</td>
                        <td class="py-3 px-6 border-b border-gray-300">${{ item.total_price }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="mt-6 flex justify-between items-center">
            <h3 class="text-lg font-semibold text-gray-800">Total Amount: <span class="font-normal text-green-600">${{ total_amount }}</span></h3>
            <form method="post" action="{% url 'payments:checkout' payment.id %}">
                {% csrf_token %}
                <button type="submit" class="bg-green-600 text-white px-6 py-3 rounded-lg shadow-lg hover:bg-green-800 transition duration-300">Place Order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

payments/templates/payments/payment_failed.html
{% extends 'payments/base.html' %}
{% load static %}

{% block title %}Payment Failed{% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <div class="bg-white p-6 rounded-lg shadow-lg text-center">
        <div class="flex justify-center items-center mb-4">
            <div class="w-24 h-24 bg-white flex items-center justify-center">
                <svg class="w-16 h-16 text-red-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm2.707-11.293a1 1 0 00-1.414 0L10 8.586 8.707 7.293a1 1 0 10-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 101.414-1.414L11.414 10l1.293-1.293a1 1 0 000-1.414z" clip-rule="evenodd"/>
                </svg>
            </div>
        </div>
        <h1 class="text-4xl font-bold text-red-600">Payment Failed!</h1>
        <p class="mt-4 text-gray-600">There was an error processing your payment. Please try again.</p>
        <div class="mt-6">
            <a href="{% url 'payments:checkout' payment_id %}" class="inline-block px-6 py-2 text-white bg-red-600 rounded-lg shadow-lg hover:bg-red-700 transition-all duration-300 ease-in-out">
                Try Again
            </a>
        </div>
    </div>
</div>
{% endblock %}

payments/templates/payments/payment_form.html
{% extends 'payments/base.html' %}
{% load static %}

{% block title %}Payment Page{% endblock %}

{% block extra_css %}
{#<link rel="stylesheet" href="{% static 'payments/styles.css' %}">#}
{% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h1 class="text-3xl text-green-700 font-bold mb-8 text-center">Payment</h1>
    <form method="post" class="max-w-lg mx-auto bg-white p-6 rounded-lg shadow-lg space-y-6">
        {% csrf_token %}
        <div class="space-y-4">
            <div>
                <label for="id_Name" class="block text-gray-700 font-bold mb-2">Name</label>
                {{ form.Name }}
            </div>
            <div>
                <label for="id_address" class="block text-gray-700 font-bold mb-2">Address</label>
                {{ form.address }}
            </div>
            <div>
                <label for="id_zipcode" class="block text-gray-700 font-bold mb-2">Zipcode</label>
                {{ form.zipcode }}
            </div>
            <div>
                <label for="id_country" class="block text-gray-700 font-bold mb-2">Country</label>
                {{ form.country }}
            </div>
            <div>
                <label for="id_city" class="block text-gray-700 font-bold mb-2">City</label>
                {{ form.city }}
            </div>
            <div>
                <label for="id_Email" class="block text-gray-700 font-bold mb-2">Email</label>
                {{ form.Email }}
            </div>
        </div>
        <button type="submit" class="w-full bg-green-600 text-white py-2 px-4 rounded hover:bg-green-800 transition duration-300">Pay Now</button>
    </form>
</div>
{% endblock %}

payments/templates/payments/payment_success.html
{% extends 'payments/base.html' %}
{% load static %}

{% block title %}Payment Success{% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <div class="bg-white p-6 rounded-lg shadow-lg text-center">
        <div class="flex justify-center items-center mb-4">
            <div class="w-24 h-24 bg-white rounded-full border-4 border-green-500 flex items-center justify-center animate-bounce">
                <svg class="w-16 h-16 text-green-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 00-1.414-1.414L8 11.586 4.707 8.293a1 1 0 00-1.414 1.414l4 4a1 1 0 001.414 0l8-8z" clip-rule="evenodd"/>
                </svg>
            </div>
        </div>
        <h1 class="text-4xl font-bold text-green-600">Payment Successful!</h1>
        <p class="mt-4 text-gray-600">Your payment has been processed successfully.</p>
        <p class="mt-4 text-gray-500">Thank you for your purchase.</p>
        <div class="mt-6">
            <a href="{% url 'Shop:home' %}" class="inline-block px-6 py-2 text-white bg-green-600 rounded-lg shadow-lg hover:bg-green-700 transition-all duration-300 ease-in-out">
                Continue Shopping
            </a>
        </div>
    </div>
</div>
{% endblock %}