Auth/urls.py
from django.urls import path
from .views import Signup, Login, logout_view, forgot_password,reset_password
app_name = 'Auth'

urlpatterns = [
    path('signup/', Signup.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    path('reset_password/', reset_password, name='reset_password'),
]

GreenCart/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
admin.site.site_header="GreenCart Admin"
admin.site.site_title ="GreenCart Admin Portal"
from payments.views import payment_view, payment_success

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GreenCartEcom.urls','GreenCartEcom'), name='GreenCartEcom'),
    path('cart/', include('add_to_cart.urls', 'AddToCart'), name='AddToCart'),
    path('auth/', include('Auth.urls','Auth'), name='Auth'),
    path('shop/', include('Shop.urls','Shop'), name='Shop'),
    path('profile/', include('userprofile.urls','Profile'), name='Profile'),
    path('pay/', include(('payments.urls', 'payments'), namespace='payments')),
    path('support/', include('Support.urls'), name='Support')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GreenCartEcom/urls.py
from django.urls import path
from . import views

app_name = 'GreenCartEcom'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms-and-conditions/', views.terms_and_conditions, name='terms_and_conditions'),
    path('gardening-guides/', views.gardening_guides, name='gardening_guides'),
    path('plant-care-tips/', views.plant_care_tips, name='plant_care_tips'),
    path('subscribe/', views.subscribe, name='subscribe'),
    
]

Shop/urls.py
from django.urls import path
from .views import clear_search_history, home, product_detail, product_list, create_product, edit_product, delete_product, manage_reviews, delete_review ,edit_review

app_name = 'Shop'

urlpatterns = [
    path('',home, name='home'),
    path('cart/',home, name='cart'),
    path('checkout/',home, name='checkout'),
    path('order/',home, name='order'),
    path('profile/',home, name='profile'),
    path('product-detail/<int:id>', product_detail, name='product_detail'),
    path('mylistings/', product_list, name='product_list'),
    path('create_product/', create_product, name='create_product'),
    path('edit_product/<int:product_id>/', edit_product, name='edit_product'),
    path('delete_product/', delete_product, name='delete_product'),
    path('clear_search_history/', clear_search_history, name='clear_search_history'),
    path('manage_reviews/',manage_reviews, name='manage_reviews'),
    path('edit/<int:review_id>/', edit_review, name='edit_review'),
    path('delete/<int:review_id>/', delete_review, name='delete_review'),
]

Support/urls.py
# Support/urls.py

from django.urls import path
from . import views


app_name = 'support'

urlpatterns = [
    path('', views.support_home, name='support-home'),
    path('submit-query/', views.query_form, name='submit_query'),
    path('query-success/', views.query_sucess, name='query_success'),
    path('track-ticket/', views.track_ticket, name='track_ticket'),
    path('ticket-input/', views.ticket_input, name='ticket_input'),
    path('update-status/<int:ticket_number>/', views.update_status, name='update_status'),
    path('update-success/', views.update_sucess, name='update_success'),
    path('faq/', views.faq, name='faq'),
]

add_to_cart/urls.py
from django.urls import path
from . import views

app_name = 'add_to_cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('increment/<int:cart_item_id>/', views.increment_quantity, name='increment_quantity'),
    path('decrement/<int:cart_item_id>/', views.decrement_quantity, name='decrement_quantity'),
    path('add_to_wishlist/<int:cart_item_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('remove_from_wishlist/<int:wishlist_item_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('add_to_wishlist/product/<int:product_id>/', views.add_to_wishlist, name='add_product_wishlist'),
    path('add_from_wishlist/<int:product_id>/', views.add_to_cart_from_wishlist, name='add_to_cart_from_wishlist'),
]

Shop/models.py
from datetime import timedelta

from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver

from Auth.models import User


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    expiry = models.IntegerField(default=3)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    image = models.ImageField(default='default.jpg', upload_to='products/')
    in_stock = models.BooleanField(default=True)
    rating = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_id = models.CharField(max_length=10,default="1")
    expiry_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name
    
    def expire_date(self):
        return self.created_at + timedelta(days=self.expiry)

    def days_left(self):
        now = timezone.now()
        expire_date = self.expire_date()
        delta = expire_date - now
        return delta.days + 1


class Reviews(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    review = models.TextField()
    rating = models.DecimalField(max_digits=3, decimal_places=2, default=0.0)

@receiver(post_save, sender=Product)
def set_expiry_date(sender, instance, created, **kwargs):
    if created:
        instance.expiry_date = instance.created_at + timedelta(days=instance.expiry)
        instance.save()
    else:
        Product.objects.filter(id=instance.id).update(
            expiry_date=instance.created_at + timedelta(days=instance.expiry)
        )

Shop/views.py
from datetime import datetime
import pytz
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from .models import Product, Reviews
from .forms import ProductForm, ReviewForm
from django.shortcuts import render, redirect
from userprofile.models import UserProfile


def navbar(request):
    if request.user.is_authenticated:
        return render(request, 'navbar.html',
                      {'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url})
    else:
        return render(request, 'Dashboard/navbar.html')


@login_required
def home(request):
    ### Retrieving Query Parameters
    query = request.GET.get('query', '')
    min_price = request.GET.get('min_price', 0)
    max_price = request.GET.get('max_price', 1000000)
    min_rating = request.GET.get('min_rating', 0)
    sort_by = request.GET.get('sort_by', '')

    ### Initial Product Query

    products = Product.objects.filter(expiry_date__gte=datetime.now(), in_stock=True)
    
    ### Greeting Message based on time
    timezone = pytz.timezone('America/New_York')
    current_hour = datetime.now(timezone).hour
    if current_hour < 12:
        greeting = "Good morning"
    elif 12 <= current_hour < 18:
        greeting = "Good afternoon"
    else:
        greeting = "Good evening"

    ### User Name
    user_name = request.user.first_name

    ### Handling Search History
    # Retrieves the search history from cookies and splits it into a list.
    search_history = request.COOKIES.get('search_history', '')
    search_history = search_history.split(',') if search_history else []

    ### Filtering Products Based on Query
    if query:
        products = products.filter(name__icontains=query)
        # Store the search query in cookies
        if query not in search_history:
            search_history.append(query)
            search_history_cookie = ','.join(search_history)
        else:
            search_history_cookie = ','.join(search_history)

    ### Filtering Products Based on Price and Rating
    if min_price:
        products = products.filter(discount_price__gte=min_price)

    if max_price:
        products = products.filter(discount_price__lte=max_price)

    if min_rating:
        products = products.filter(rating__gte=min_rating)

    ### Sorting Products based on expiry date
    if sort_by == 'expiry_asc':
        products = products.order_by('expiry')
    elif sort_by == 'expiry_desc':
        products = products.order_by('-expiry')


    response = render(request, 'Shop/home.html', {
        'products': products,
        'greeting': greeting,
        'user_name': user_name,
        'title': 'GreenCart | Home',
        'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url,
        'search_history': search_history,
    })

    ### Set the search history cookie
    if query:
        response.set_cookie('search_history', search_history_cookie, max_age=365*24*60*60)  # Cookie expires in one year

    return response

@login_required
def clear_search_history(request):
    response = redirect('Shop:home')
    response.delete_cookie('search_history')
    return response

    
@login_required
def product_detail(request, id):
    if request.method == 'POST':
        product = get_object_or_404(Product, pk=id)
        # name = request.POST.get('name')
        review = request.POST.get('review')
        rating = request.POST.get('rating')
        if str.strip(review) and rating:
            Reviews.objects.create(product=product,user= request.user, review=review, rating=rating)
            reviews = Reviews.objects.filter(product=product)
            cal_rating = 0
            if reviews:
                for review in reviews:
                    cal_rating += review.rating
                cal_rating = round(cal_rating / len(reviews), 1)
                product.rating = float(cal_rating)
                product.save()
            return redirect('Shop:product_detail', id=id)
        else:
            reviews = Reviews.objects.filter(product=product)
            return render(request, 'Shop/product-detail.html',
                          {'product': product, 'reviews': reviews, 'rating': product.rating,
                           'user_profile_pic': UserProfile.objects.get(
                               user=request.user).profile_pic.url})
    else:
        product = get_object_or_404(Product, pk=id)
        reviews = Reviews.objects.filter(product=product)
        return render(request, 'Shop/product-detail.html',
                      {'product': product, 'reviews': reviews, 'rating': product.rating,
                       'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url})


@login_required
def product_list(request):
    user = request.user
    products = Product.objects.filter(user_id=user.id)
    return render(request, 'Shop/product_list.html', {'products': products, 'user_profile_pic': UserProfile.objects.get(
        user=request.user).profile_pic.url})


@login_required
def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user_id = request.user.id
            product.created_at = datetime.now()
            product.updated_at = datetime.now()
            product.save()
        return redirect('Shop:product_list')  # Redirect to the product list or another appropriate page
    else:
        form = ProductForm()
    return render(request, 'Shop/create_product.html',
                  {'form': form, 'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url})


@login_required
def edit_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.updated_at = datetime.now()
            product.save()
            return redirect('Shop:product_list')
    else:
        form = ProductForm(instance=product)

    return render(request, 'Shop/edit_product.html',
                  {'form': form, 'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url,
                   'product': product})


@login_required
def delete_product(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        product = get_object_or_404(Product, id=product_id)
        product.delete()
        return redirect('Shop:product_list')

@login_required
def manage_reviews(request):
    reviews = Reviews.objects.filter(user=request.user)
    print(reviews)
    return render(request,'Shop/manage-review.html',{'reviews':reviews, 'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url})

@login_required
def edit_review(request, review_id):
    review = get_object_or_404(Reviews, id=review_id)
    print(review)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            cal_product = review.product
            cal_reviews = Reviews.objects.filter(product=cal_product)
            cal_rating = 0
            if cal_reviews:
                for cal_review in cal_reviews:
                    cal_rating += cal_review.rating
                cal_rating = round(cal_rating / len(cal_reviews), 1)
                cal_product.rating = float(cal_rating)
                cal_product.save()
            return redirect("Shop:manage_reviews")
    else:
        form = ReviewForm(instance=review)
    return render(request, 'Shop/edit_review.html', {'form': form,'review_id':review_id, 'user_profile_pic': UserProfile.objects.get(user=request.user).profile_pic.url})

@login_required
def delete_review(request, review_id):
    review = get_object_or_404(Reviews, id=review_id)
    print(review)
    cal_product = review.product
    review.delete()
    cal_reviews = Reviews.objects.filter(product=cal_product)
    cal_rating = 0
    if cal_reviews:
        for cal_review in cal_reviews:
            cal_rating += cal_review.rating
        cal_rating = round(cal_rating / len(cal_reviews), 1)
        cal_product.rating = float(cal_rating)
        cal_product.save()
    else:
        cal_product.rating = 0
        cal_product.save()
    return redirect('Shop:manage_reviews')

Shop/templates/Shop/create_product.html
<!-- create_product.html -->

{% extends 'Shop/base.html' %}
{% load static %}

{% block content %}
<div class="container mx-auto p-6">
    <div class="bg-white shadow-lg rounded-lg p-6 flex">
        <div class="w-1/2 pr-6">
            <h1 class="text-3xl font-bold mb-5 text-green-700">Add New Product</h1>
            <form method="post" enctype="multipart/form-data" class="space-y-4">
                {% csrf_token %}
                <div>
                    <label for="id_in_stock" class="block text-sm font-medium text-gray-700">In Stock</label>
                    <label class="inline-flex items-center cursor-pointer">
                        {{ form.in_stock }}
                        <div class="relative w-11 h-6 bg-gray-200 peer-focus:outline-none  dark:peer-focus:ring-green-800 rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-green-600"></div>
                    </label>
                </div>
                <div>
                    <label for="id_name" class="block text-sm font-medium text-gray-700">Name</label>
                    {{ form.name }}
                </div>
                <div>
                    <label for="id_description" class="block text-sm font-medium text-gray-700">Description</label>
                    {{ form.description }}
                </div>
                <div>
                    <label for="id_price" class="block text-sm font-medium text-gray-700">Price</label>
                    {{ form.price }}
                </div>
                <div>
                    <label for="id_expiry" class="block text-sm font-medium text-gray-700">Expiry (in days)</label>
                    {{ form.expiry }}
                </div>
                <div>
                    <label for="id_discount_price" class="block text-sm font-medium text-gray-700">Discounted Price</label>
                    {{ form.discount_price }}
                </div>
                <div>
                    <label for="id_image" class="block text-sm font-medium text-gray-700">Upload image of product</label>
                    {{ form.image }}
                </div>
                <button type="submit" class="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded mt-4">Save</button>
            </form>
        </div>
        <div class="w-1/2 pl-6 flex items-center justify-center">
            <div class="w-full h-full border-dashed border-4 border-gray-200 rounded-lg p-4 flex items-center justify-center">
                <img id="product-image-preview" src="{% if form.instance.image %}{{ form.instance.image.url }}{% else %}{% static 'images/default.jpg' %}{% endif %}" alt="Product Image" class="max-w-full max-h-full object-cover rounded">
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('id_image').addEventListener('change', function(event) {
        const [file] = event.target.files;
        if (file) {
            const preview = document.getElementById('product-image-preview');
            preview.src = URL.createObjectURL(file);
            preview.onload = () => URL.revokeObjectURL(preview.src);
        }
    });
</script>
{% endblock %}

Shop/templates/Shop/edit_product.html
<!-- edit_product.html -->

{% extends 'Shop/base.html' %}
{% load static %}

{% block content %}
<div class="container mx-auto p-6">
    <div class="bg-white shadow-lg rounded-lg p-6 flex">
        <div class="w-1/2 pr-6">
            <h1 class="text-3xl font-bold mb-5 text-green-700">Edit Product</h1>
            <form method="post" enctype="multipart/form-data" class="space-y-4">
                {% csrf_token %}
                <div>
                    <label for="id_in_stock" class="block text-sm font-medium text-gray-700">In Stock</label>
                    <label class="inline-flex items-center cursor-pointer">
                        {{ form.in_stock }}
                        <div class="relative w-11 h-6 bg-gray-200 peer-focus:outline-none  dark:peer-focus:ring-green-800 rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-green-600"></div>
                    </label>
                </div>
                <div>
                    <label for="id_name" class="block text-sm font-medium text-gray-700">Name</label>
                    {{ form.name }}
                </div>
                <div>
                    <label for="id_description" class="block text-sm font-medium text-gray-700">Description</label>
                    {{ form.description }}
                </div>
                <div>
                    <label for="id_price" class="block text-sm font-medium text-gray-700">Price</label>
                    {{ form.price }}
                </div>
                <div>
                    <label for="id_expiry" class="block text-sm font-medium text-gray-700">Expiry (in days)</label>
                    {{ form.expiry }}
                </div>
                <div>
                    <label for="id_discount_price" class="block text-sm font-medium text-gray-700">Discounted Price</label>
                    {{ form.discount_price }}
                </div>
                <div>
                    <label for="id_image" class="block text-sm font-medium text-gray-700">Upload image of product</label>
                    {{ form.image }}
                </div>
                <button type="submit" class="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded mt-4">Save</button>
            </form>
        </div>
        <div class="w-1/2 pl-6 flex items-center justify-center">
            <div class="w-full h-full border-dashed border-4 border-gray-200 rounded-lg p-4 flex items-center justify-center">
                <img id="product-image-preview" src="{% if form.instance.image %}{{ form.instance.image.url }}{% else %}{% static 'images/default.jpg' %}{% endif %}" alt="Product Image" class="max-w-full max-h-full object-cover rounded">
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('id_image').addEventListener('change', function(event) {
        const [file] = event.target.files;
        if (file) {
            const preview = document.getElementById('product-image-preview');
            preview.src = URL.createObjectURL(file);
            preview.onload = () => URL.revokeObjectURL(preview.src);
        }
    });
</script>
{% endblock %}

Shop/templates/Shop/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
<nav class="py-5 flex-wrap bg-green-100/75">
    <div class="container mx-auto px-6 md:px-0">
        <div class="flex items-center justify-between">

            <div class="flex items-center">
                <a href="/shop" class="flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse">
                    <img src="{% static 'images/logo.png' %}" class="h-8" alt="GreenCart Logo" />
                </a>
            </div>

            <!-- Navigation Links (Visible on larger screens) -->
            <div class="hidden md:flex items-center space-x-4 relative">
                <a href="{% url 'AddToCart:cart' %}" class="pr-4 text-green-500/50 hover:text-green-600 text-lg font-semibold">Cart</a>
                <a href="{% url 'AddToCart:wishlist' %}" class="pr-4 text-green-500/50 hover:text-green-600 text-lg font-semibold">Wishlist</a>
                <a href="{% url 'Shop:product_list' %}" class="pr-4 text-green-500/50 hover:text-green-600 text-lg font-semibold">My Listings</a>
                <a href="{% url 'support:support-home' %}" class="pr-4 text-green-500/50 hover:text-green-600 text-lg font-semibold">Support</a>
                <a href="{% url 'GreenCartEcom:about' %}" class="pr-4 text-green-500/50 hover:text-green-600 text-lg font-semibold">About Us</a>
                <img id="avatar" class="w-10 h-10 rounded-full cursor-pointer hover:border"  src="{{ user_profile_pic }}" alt="Rounded avatar">
                <div id="dropdown"  class="hidden absolute right-0 top-full mt-2 w-48 bg-white rounded-md shadow-lg py-2 z-20">
                    <a href="{% url 'Profile:get_user_details' %}" class="block px-4 py-2 text-green hover:bg-gray-100">Profile</a>
                    <a href="{% url 'Auth:logout' %}" class="block px-4 py-2 text-green hover:bg-gray-100">Logout</a>
                </div>
            </div>

            <script>
                document.getElementById('avatar').addEventListener('click', function() {
                    const dropdown = document.getElementById('dropdown');
                    if (dropdown.classList.contains('hidden')) {
                        dropdown.classList.remove('hidden');
                    } else {
                        dropdown.classList.add('hidden');
                    }
                });

                // Close the dropdown if the user clicks outside of it
                document.addEventListener('click', function(event) {
                    const dropdown = document.getElementById('dropdown');
                    const avatar = document.getElementById('avatar');
                    if (!dropdown.contains(event.target) && !avatar.contains(event.target)) {
                        dropdown.classList.add('hidden');
                    }
                });
            </script>
        </div>
    </div>
</nav>
</body>
</html>

Shop/templates/Shop/product_list.html
{% extends 'Shop/base.html' %}
{% block title %}GreenCart | My Listings {% endblock %}


{% block content %}
    <div class="container mx-auto p-6">
        <div class="w-100 flex justify-between items-center p-0">
            <h1 class="text-3xl font-bold mb-5 p-0 m-0 text-green-800">Product List</h1>
            <a href="{% url 'Shop:create_product' %}" class="block mt-4">
                <button class="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg">Add New Product</button>
            </a>
        </div>
        {% if products %}
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mt-5">
                {% for product in products %}
                    <div class="relative mx-auto my-6 w-full max-w-xs flex-col overflow-hidden rounded-lg bg-white shadow-md">
                        <a class="relative flex h-60 overflow-hidden rounded-t-lg group"
                           href="{% url 'Shop:edit_product' product.id %}">
                            <img class="object-cover w-full transform transition-transform duration-500 group-hover:scale-110"
                                 src="{{ product.image.url }}" alt="{{ product.name }}">
                            {% if product.days_left >= 0 %}
                                <span class="absolute top-0 left-0 m-2 rounded-full bg-red-600 px-2 text-center text-sm font-medium text-white">
                                {% if product.days_left > 0 %}
                                    {{ product.days_left }} days left
                                {% else %}
                                    Expired
                                {% endif %}
                                </span>
                            {% endif %}
                        </a>
                        <div class="mt-4 px-5 pb-5">
                            <a href="{% url 'Shop:edit_product' product.id %}">
                                <h5 class="text-xl font-semibold tracking-tight h-16 text-slate-900">{{ product.name }}</h5>
                            </a>
                            <p class="text-gray-700 mb-4">
                                {{ product.description|slice:":60" }}{% if product.description|length > 60 %}
                                    ...{% endif %}
                            </p>
                            <div class="mt-2 mb-5 flex items-center">
                                {% for i in "12345" %}
                                    <svg aria-hidden="true"
                                         class="h-5 w-5 {% if product.rating|floatformat:1 >= i %}text-yellow-300{% else %}text-gray-300{% endif %}"
                                         fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                                    </svg>
                                {% endfor %}
                                <span class="ml-2 rounded bg-yellow-200 px-2.5 py-0.5 text-xs font-semibold">{{ product.rating }}</span>
                            </div>
                            <div class="flex items-center justify-between">
                                {% if product.discount_price %}
                                    <span class="text-3xl font-bold text-slate-900">${{ product.discount_price }}</span>
                                    <span class="text-sm text-slate-900 line-through">${{ product.price }}</span>
                                {% else %}
                                    <span class="text-3xl font-bold text-slate-900">${{ product.price }}</span>
                                {% endif %}
                                <button onclick="showModal('{{ product.id }}', '{{ product.name }}', '{{ product.image.url }}')"
                                        class="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded text-center">
                                    Delete
                                </button>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="flex items-center justify-center h-full">
                <div class="text-center">
                    <h2 class="text-2xl font-bold mb-4 text-green-800">No Products Listed</h2>
                    <p class="text-gray-700 mb-4">You haven't listed any products yet.</p>
                    <a href="{% url 'Shop:create_product' %}" class="block mt-4">
                        <button class="bg-green-600 hover:bg-green-800 text-white px-4 py-2 rounded">Add New Product
                        </button>
                    </a>
                </div>
            </div>
        {% endif %}
    </div>

    <!-- Delete Modal -->
    <div id="deleteModal" class="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center hidden">
        <div class="bg-white rounded-lg shadow-lg p-6 w-1/3">
            <h2 class="text-xl font-bold mb-4">Delete Product</h2>
            <img id="modal-product-image" src="" alt="Product Image" class="w-full h-48 object-cover rounded mb-4">
            <p class="text-gray-700 mb-4">Are you sure you want to delete <span id="modal-product-name"
                                                                                class="font-semibold"></span>?</p>
            <form action="{% url 'Shop:delete_product' %}" method="post" class="flex justify-between">
                {% csrf_token %}
                <input type="hidden" id="modal-product-id" name="product_id" value="">
                <button type="button" onclick="hideModal()"
                        class="bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded">Cancel
                </button>
                <button type="submit" class="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg">
                Yes
                </button>
            </form>
        </div>
    </div>
{% endblock %}